version: '3'

services:
  web:
    build: .
    command: gunicorn messaging_system.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
      - logs:/code/logs
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  logs: